### ISSUE TITLE
SparseTICA partial_transform method execution time

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/msmbuilder#1037]
I'm trying out different decomposition algorithms on a featurized dataset. Both the regular tICA and the PCA classes fit the data in several seconds (the shape of the input dataset is `(199062, 2415)`)).

The sparse tica object fit method is also quick on the full dataset. Nevertheless, when I try to project the trajectories, it gets stuck. I've also tried only projecting 10 frames and it also doesn't seem to finish. Is this behaviour expected?

This is the Sparse Tica object that I create:
```
SparseTICA(epsilon=1e-06, kinetic_mapping=True, lag_time=5, maxiter=10000,
      n_components=5, rho=0.01, shrinkage=None, tolerance=1e-06,
      verbose=False)
```

**Comment by msultan** [comment]
The SparseTica model doesn't actually perform the eigendecomposition until after you call the transform method on it. IIRC it also uses an iteration based algorithm which makes it slower. I have gotten it to work with >3500 features BUT it takes several hours to run. Just let it run with the entire dataset overnight.
Also, I would recommend dumping the SparseModel AFTER you are done transforming so that it keeps a copy of the eigenvectors for future use.

**Comment by jeiros** [comment]
Ahh, that's good to know. Thanks!
