### ISSUE TITLE
lag time and macrostate structures

### ISSUE THREAD

**Issue by mohanpradhan** [msmbuilder/msmbuilder#1056]
Hi,

I am using msmbuilder 3.8. I have the following doubts. Any help is highly appreciated.

1] How do I interpret the attached (timescales vs lag time) plot? What is the appropriate lag time that I should chose for my model?
![implied_timescales](https://user-images.githubusercontent.com/32761146/33160045-193750a6-d054-11e7-8e60-01af7333c919.png)

2] In the msm building step (microsate.py), the program is able to build only 5 macrostates even when I specify n_macrostates=10. ### pcca = PCCAPlus.from_msm(msm, n_macrostates=10).
![edge csv](https://user-images.githubusercontent.com/32761146/33160192-286a5234-d055-11e7-8651-5ca3f35d388f.png)

Any idea why this this is so?

3] How do i extract structures (or trajectories) corresponding to these 5 macrostates?
This is how I am trying to do. But I am not sure if this is right. 
From macrostate to microstate mapping I get a microstate corresponding to a particular macrostate (One issue here is that every time I run the microstate.py program, I get a different mapping array- pcca.microstate_mapping_ . Not sure why is that!).
Then I look into the output of cluster.py --> kmeans.labels_ and try to map the microstates on frame nos.

**Comment by msultan** [comment]
> 1] How do I interpret the attached (timescales vs lag time) plot? What is the appropriate lag time that I should chose for my model?
Any thing between 1 -10 seems alright to me. 

> 2] In the msm building step (microsate.py), the program is able to build only 5 macrostates even when I specify n_macrostates=10. ### pcca = PCCAPlus.from_msm(msm, n_macrostates=10).
How many states were in your clustering model? Did the msm throw away any data. The usual times this happens is when the MSM has only 5-9 states to start with, and you end up asking for 10 so it sorta defaults. 

3] How do i extract structures (or trajectories) corresponding to these 5 macrostates?
This is how I am trying to do. But I am not sure if this is right.
From macrostate to microstate mapping I get a microstate corresponding to a particular macrostate (One issue here is that every time I run the microstate.py program, I get a different mapping array- pcca.microstate_mapping_ . Not sure why is that!).
Yea thats how its supposed to be. I think PCCAPlus is stochastic so its gonna have some randomness to it but ( Macrostate 1 is now 2 etc) but I wouldnt worry too much about it since its just changing the labels and not the actual assignments. You can always dump (using msmbuilder.utils.dump) the model for later use or alternatively set the numpy's random seed generator. @brookehus has implemented both BACE and a new more robust macrostating algorithm MVCA which I believe are not stochastic so it might be worth looking into those.

**Comment by Nidane** [comment]
@mohanpradhan excuse me, may I ask you how to extract structures or trajectories from the MSM that built through the MSMBuilder ? I read about your previous description and I am wondering how you interpretate the kmeans.pickl and ktrajs file produced by the cluster.py ? Also, after that how do you obtain the corresponding structures or trajectory ? by analyzing the trajectory that constructed based on the MSM from microstate.py I guess?
Thank you very much if you could please provide any help.
