### ISSUE TITLE
Error tica.py line 405

### ISSUE THREAD

**Issue by oni-sama14** [msmbuilder/msmbuilder#1060]
Hey,

Just so you're aware, I am an undergraduate student hoping to use MSMBuilder for my thesis so I am not particularly skilled with numerical computations, etc.

I am trying to use to tICA function for my data set, but it keeps returning: 
"UserWarning: The number of features (1000) is greater than the length of the data (1536). The covariance matrix is not guaranteed to be positive definite." 

I am having trouble working out the issue. Anyone know any literature that may be useful / have any advice?

**Comment by cxhernandez** [comment]
Note that this is just a warning, not an error, and if you obtain a valid tICA model then things should be working fine. Also, note there used to be a typo in that print statement (which recently has been fixed) that mixes up the number of features with the trajectory length.

That particular warning is due to issues that may arise in estimating a high-dimensional correlation matrix when you have relatively small sample sizes (e.g. more features than data-points). Although covariance matrices are by definition positive-definite, numerical estimators of this matrix may fall short.  The [Rao-Blackwell Ledoit-Wolf estimator](http://tbayes.eecs.umich.edu/_media/yilun/covestimation/chen_icassp1_09.pdf) used is meant to help in this case but I do not believe there's any numerical guarantee that it will be positive-definite if the number of samples is small enough.
