### ISSUE TITLE
Free energy projections on Feature different from that used for MSM

### ISSUE THREAD

**Issue by enaziga** [msmbuilder/msmbuilder#1064]
Hi All,

I have a bunch of trajectories that I have analysed along the lines of:
https://github.com/msmbuilder/msmbuilder/issues/1021

I used something like:
data = np.concatenate(tica_traj, axis=0)
pi_0 = msm.populations_[np.concatenate(assignments, axis=0)]

And MSMExplorer to plot free energy like so:
msme.plot_free_energy(data, obs=(0, 1), n_samples=250000, pi=pi_0) which does a plot of the first 2 tICA components and free energy as a heatmap.

My question is if there is a straight forward way to do free energy plots using other parameters like a RMSD seeing as my cluster assignments were done in tICA space. I think a round about way might be to use the tICA index to retrieve the particular snapshot, calculate RMSD and feed that as data to the msme.plot_free_energy function.

Thanks,
Emmanuel

**Comment by msultan** [comment]
yea, pretty much since the MSM object doesn't really have any way of computing that observable on its own. 

The first way would be to calculate the RMSD for each frame and then follow the process above. However, that is gonna be super expensive if you have billions of data points. 

A second alternative would be to compute the observable RMSD for a subset of the data (say 100-500 randomly sampled frames from each microstate) and then follow the same procedure as above. Just make sure to keep the indices in check here so that you dont accidently swap observable for state 0 with 1 etc ( i have definitely done that accidentally ).

**Comment by enaziga** [comment]
Thanks, I'll give it a try
