### ISSUE TITLE
implied_timescales ergodic cutoff inconsistency

### ISSUE THREAD

**Issue by spetznova** [msmbuilder/msmbuilder#617]
The default ergodic cutoff when using implied_timescales (1.0) is different than the default value when calling MarkovStateModel directly (1.0 / lag_time), when using a sliding window.

**Comment by mpharrigan** [comment]
The reason why this happens is the logic for transforming the default value of `ergodic_trimming='on'` into a number passed to the maximally-connected-subgraph code is done during `__init__()`. This number is set to `1/lag_time` because the counts matrix is normalized by the number of windows when `sliding_window=True`. 

In `implied_timescales`, the `lag_time` parameter is set *after* the `MarkovStateModel` object is constructed.

A temporary workaround is to pass a very small value to ergodic_cutoff (i.e. < (1/max_lag_time))

A fix would be to move the logic which is currently in `__init__` into the `fit()` function
