### ISSUE TITLE
Error using  msmb DihedralFeaturizer + tICA

### ISSUE THREAD

**Issue by lguarneros** [msmbuilder/msmbuilder#682]
Hi..
When I use the featurizer dihedral I have the next result:

/home/guarnerols$msmb DihedralFeaturizer --out featurizer.pkl --transformed diheds --top ionized.pdb --trjs "DCD/*.dcd"
DihedralFeaturizer(sincos=True, types=['phi', 'psi'])
100%|################################################################################################################################|Time: 0:10:38

Saving transformed dataset to 'diheds/'
To load this dataset interactive inside an IPython
shell or notebook, run

  $ ipython
  >>> from msmbuilder.dataset import dataset
  >>> ds = dataset('diheds/')

Saving "featurizer.pkl"... (<class 'msmbuilder.featurizer.featurizer.DihedralFeaturizer'>)
To load this DihedralFeaturizer object interactively inside an IPython
shell or notebook, run: 

  $ ipython
  >>> from msmbuilder.utils import load
  >>> model = load('featurizer.pkl')

And then I applied the next command:

/home/guarneros$ msmb tICA -i diheds/ --out tica_model.pkl --transformed tica_trajs.h5 --n_components 4
tICA(gamma=0.05, lag_time=1, n_components=4, weighted_transform=False)
Fitting model...
An unexpected error has occurred with MSMBuilder (version 3.3.0), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/opt/anaconda/bin/msmb", line 6, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/opt/anaconda/lib/python2.7/site-packages/msmbuilder/cmdline.py", line 440, in start
    instance.start()
  File "/opt/anaconda/lib/python2.7/site-packages/msmbuilder/commands/fit_transform.py", line 58, in start
    self.instance.fit(inp_ds)
  File "/opt/anaconda/lib/python2.7/site-packages/msmbuilder/decomposition/tica.py", line 262, in fit
    self._fit(X)
  File "/opt/anaconda/lib/python2.7/site-packages/msmbuilder/decomposition/tica.py", line 366, in _fit
    X = np.asarray(array2d(X), dtype=np.float64)
  File "/opt/anaconda/lib/python2.7/site-packages/msmbuilder/utils/validation.py", line 62, in array2d
    _assert_all_finite(X_2d)
  File "/opt/anaconda/lib/python2.7/site-packages/msmbuilder/utils/validation.py", line 74, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

What's the problem? Is the same error with ContactFeaturizer

**Comment by rmcgibbo** [comment]
Can you try putting the output [inside triple backticks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks), so it'll be easier to read?

**Comment by rmcgibbo** [comment]
It looks like the issue is that your dihedral angle data contains NaNs or Infinities. You should be able to check that out by following the printed instructions to load the dihedral data in IPython, looking at it there, and finding the offending frames or angles.

**Comment by lguarneros** [comment]
I'm new to this, I could provide an example?

**Comment by rmcgibbo** [comment]
Sure. I'm not sure how much I can help, because the answer might depend in part on the particularities of your data set.

- First, depending on your background in numerical computing, you may find the folllowing resources educational: http://floating-point-gui.de/, http://www.johndcook.com/blog/2009/04/06/numbers-are-a-leaky-abstraction/.
- As you might know from running MD, a common failure mode is that the simulation "explodes", or all the coordinates become `NaN`.
- Any time you have a computation involving division, you have the potential to get a `NaN` result if the denominator is zero. For example, to compute the dihedral you need to do some division and an arc-cosine. It's possible that in certain circumstances, you could get a NaN. e.g. what would the 'dihedral angle' be between 4 atoms that were all placed exactly at the origin (0,0,0)?

The MSMBuilder output that you pasted about gave instructions on how to load the dihedral data in IPython.

```
To load this dataset interactive inside an IPython shell or notebook, run

$ ipython

>>>  from msmbuilder.dataset import dataset
>>> ds = dataset('diheds/')
```

These instructions should be valid. If you type `ipython` at the terminal and then paste in those commands, the `ds` object will contain your data. Assuming you had, for example, two trajectories, you could look at the first trajectory by typing `ds[0]`, and the second trajectory by typing `ds[1]` at the IPython command prompt, and you should see the numerical data. These are 2D [numpy arrays](http://www.python-course.eu/numpy.php), containing the sin and cosine of each of the dihedral angles in each of the frames of the trajectory. You can interact with them and try to figure out where the NaNs are.
 - Is every single angle NaN, or only a subset?
 - Are all of the NaNs coming from a single row (frame in the trajectory)? This might indicate an "explosion"
 - Are all of the NaNs coming from a single column (a particular dihedral angle)? This might indicate something about that part of the protein, or the atoms that define that dihedral angle.

**Comment by rmcgibbo** [comment]
[I apologize in advance if any of that was too basic or patronizing. It's hard to know on the internet what someone's background is.]

**Comment by lguarneros** [comment]
OK thanks.
I reviewed each path .. just meeting at the end of a data array dtype = float32, this is a example of my dataset:

```
array([[-0.8920697 , -0.94970077, -0.90162861, ..., -0.60944182,
        -0.96255994, -0.5371657 ],
       [-0.92075354, -0.99894691, -0.86532336, ..., -0.65068179,
        -0.97066677, -0.78855944],
       [-0.68151343, -0.8998192 , -0.72720462, ..., -0.84992534,
        -0.95368958, -0.89020312],
       ..., 
       [-0.83092338,  0.81872767, -0.77709854, ..., -0.53884041,
         0.9428187 ,  0.99619406],
       [-0.99990457,  0.93196917, -0.94531345, ..., -0.59146589,
         0.97565764,  0.99800354],
       [-0.76833791,  0.98920333, -0.77161819, ..., -0.60825235,
         0.98760003, -0.66961229]], dtype=float32)

```

**Comment by rmcgibbo** [comment]
`np.where` and `np.isfinite` might be useful to help you locate the problem. http://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html http://docs.scipy.org/doc/numpy/reference/generated/numpy.isfinite.html

**Comment by lguarneros** [comment]
This is the output:

```
In [6]: numpy.isfinite(ds[0])
Out[6]: 
array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ..., 
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]], dtype=bool)

```
Sorry for so many questions , but I'm beginner.

**Comment by rmcgibbo** [comment]
I'm sorry, but this isn't really the appropriate forum for me to help you much more or provide this kind of tutorial. I recommend trying to interact with the data, looking through the `numpy` manual that I linked to for functions that might help, and looking into some of the excellent tutorials and books that have been published, such as materials from [software carpentry](http://software-carpentry.org/), [data carpentry](http://www.datacarpentry.org/), [Effective Computation in Physics](http://shop.oreilly.com/product/0636920033424.do), and other resources.
