### ISSUE TITLE
"edit on GitHub" takes you to non-existent page

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#728]
At least for the [GMRQ example](http://msmbuilder.org/3.3.0/examples/gmrq-model-selection.html), pressing "edit on GitHub" takes you straight to a [404](https://github.com/msmbuilder/msmbuilder/blob/master/doc/examples/gmrq-model-selection.rst).

**Comment by mpharrigan** [comment]
So the reason is that the filenames have changed on github. If you look at the development docs, you'll see that I've already removed the edit on github link.

It's always really annoying to fix bugs in prior versions of the docs. What we *should* have done was had that link go to the specific github tag (commit) from which the docs were built

**Comment by mpharrigan** [comment]
somewhat relevant: https://github.com/msmbuilder/msmbuilder/issues/667#issuecomment-148570179

**Comment by mpharrigan** [comment]
This is fixed with the 3.4 docs insofaras the edit on github link is no longer there. And we're never going to go back to old docs and update that link
