### ISSUE TITLE
Implied Timescales Question

### ISSUE THREAD

**Issue by mdward** [msmbuilder/msmbuilder#953]
My slowest implied timescale does not converge as I increase the lag time (instead, the timescale keeps increasing). Eventually, the # of states connected in the model drops rather than the timescales converging. I am featurizing my data using ContactFeaturizer and then training that with tICA. I am trying to find a model that is markovian by systematically changing the tICA decorrelation lag time and the # of components being used, but I'm not having luck. How can I figure out if the issue lies in the amount of data I have OR if its in the parameters I'm choosing for the model? Also, if the 2nd and 3rd implied timescales do converge does that mean the model is markovian for those processes? 

Best,
Mick

**Comment by cxhernandez** [comment]
Hey @mdward,

> I am trying to find a model that is markovian by systematically changing the tICA decorrelation lag time and the # of components being used, but I'm not having luck

Determining the convergence of your timescales is typically done by varying the MSM lagtime, rather than the tICA lagtime. Normally you pick a set of "good" parameters in your model and then observe how the implied timescales vary across different lagtimes for the same set of parameters.

> How can I figure out if the issue lies in the amount of data I have OR if its in the parameters I'm choosing for the model? 

I'd recommend looking into [cross-validating your model using the generalized matrix Rayleigh quotient (GMRQ)](http://msmbuilder.org/3.6.0/examples/GMRQ-Model-Selection.html). If you have some reasonable estimate of your MSM lagtime, you can optimize your model systematically this way.

> Also, if the 2nd and 3rd implied timescales do converge does that mean the model is markovian for those processes?

This sounds like it could be— as you hinted— a data issue for the first that timescale. This can happen if you there's an implied timescale which has been artificially increased due to the reversibility restriction in the maximum-likelihood estimation of the MSM. You could try to increase the `ergodic_trimming` to get rid of  transitions with too few counts. Otherwise, I believe you could continue with your analysis of the other processes just fine if they seem to be converged.

**Comment by mdward** [comment]
Thanks @cxhernandez. 

I meant to say that I was testing for convergence of the implied timescales by varying the MSM lagtime and doing this for different combinations of tICA lagtime & # of components. No combination gave me convergence on the slowest process, so I did not have a reasonable estimate of the MSM lagtime. Is it worth doing the implied timescales markovian test for other parameters (i.e. basic RMSD clustering w/ no featurization & no decomposition, or different featurization & decomposition combinations) to see if I can get a model that's markovian for all timescales?

If this slowest timescale is not converging due to a data issue how do I gauge if this is something that could be remedied with a modest amount of adaptive sampling?

**Comment by cxhernandez** [comment]
>  Is it worth doing the implied timescales markovian test for other parameters (i.e. basic RMSD clustering w/ no featurization & no decomposition, or different featurization & decomposition combinations) to see if I can get a model that's markovian for all timescales?

Probably not, I'd first look into playing around with the `ergodic_cutoff` or `prior_counts` settings to identify which states/transitions seem to be involved in the slowest timescale. 

Another useful tool is looking at the [distribution of residuals between the MSM populations and the raw counts](http://msmbuilder.org/msmexplorer/0.3.0/examples/plot_pop_resids.html). Artifacts of  maximum likelihood estimation (MLE) should appear as outliers or systematic up-weighting of low count states (you can sort of see this in the example on the left end of the plot, although it's not too extreme).

> If this slowest timescale is not converging due to a data issue how do I gauge if this is something that could be remedied with a modest amount of adaptive sampling?

Depends on what "modest" means. You could do adaptive sampling, but keep in mind that in order to properly sample the slowest-process your total sampling should be at least on the same order of magnitude as said process (e.g. a millisecond of total sampling for a millisecond-long process). If you find that this slow timescale is, in fact, much longer than the total amount of sampling you have done, this could be another indication that this timescale is an artifact from the MLE of the transition matrix, and more sampling is not necessarily worth the effort.

**Comment by mdward** [comment]
Okay, thanks again @cxhernandez.  

Assuming my implied timescales converge, how do I interpret the eigenvectors associated with a timescale? The second left eigenvector will be associated with the longest timescale process and has the same number of values in it as number of states in the MSM. What do the values in the eigenvector mean? My current naive interpretation is that states with the largest difference in values are the furthest away from each other (i.e. take longer to interconvert than any other 2 states for the given process). 

If the above interpretation is true then it makes sense to plot the values in the eigenvector as a function of some order parameter to gain an intuition for the process being described. In practice how would you do this? Each state in the MSM gets a value, but conformations within a state may have slightly different order parameter values, so would you just plot 'value in eigenvector' vs. 'cluster center OP'?

**Comment by cxhernandez** [comment]
> What do the values in the eigenvector mean? My current naive interpretation is that states with the largest difference in values are the furthest away from each other (i.e. take longer to interconvert than any other 2 states for the given process).

Pretty much, you can interpret it as a "distance" along the process.

>If the above interpretation is true then it makes sense to plot the values in the eigenvector as a function of some order parameter to gain an intuition for the process being described. In practice how would you do this? Each state in the MSM gets a value, but conformations within a state may have slightly different order parameter values, so would you just plot 'value in eigenvector' vs. 'cluster center OP'?

The example section on our website might have [the answer to that](http://msmbuilder.org/3.6.0/examples/Fs-Peptide-in-RAM.html#MSM).

**Comment by mdward** [comment]
I understand how the projections in the example work. I was basically wondering how you would do something similar to supplementary figure 5 in "Conformational Heterogeneity of the Calmodulin Binding Interface".

**Comment by cxhernandez** [comment]
That appears to be free energy plot based on hand-picked features that the authors related to dynamical processes, which is somewhat different from just plotting the eigenprocesses. Take a look at the section titled "Computationally discovered metrics reveal complex dynamics" and Figure 3 to understand how they arrived at those order parameters.
